name: MacBar

options:
  createIntermediateGroups: true
  developmentLanguage: en
  deploymentTarget:
    macOS: "14.0"

settings:
  base:
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    CODE_SIGN_ENTITLEMENTS: MacBar.entitlements
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: P69755L5ZN
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_FILE: Sources/MacBar/Info.plist
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    MARKETING_VERSION: 1.0.0
    PRODUCT_BUNDLE_IDENTIFIER: app.macbar.macbar
    PRODUCT_NAME: MacBar

targets:
  MacBar:
    type: application
    platform: macOS
    settings:
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
        Release:
          CODE_SIGN_IDENTITY: 3rd Party Mac Developer Application
          CODE_SIGN_STYLE: Manual
          PROVISIONING_PROFILE: a23eeb73-9815-4c4b-aba5-0968dc906e3e
          PROVISIONING_PROFILE_SPECIFIER: MacBar App Store
    sources:
      - path: Sources/MacBar
        excludes:
          - Info.plist
          - Resources
          - .DS_Store
      - path: Sources/MacBar/Resources
        buildPhase: resources
        excludes:
          - .DS_Store
